[solana]
# Public free RPC endpoint 
ws_url = "wss://api.mainnet-beta.solana.com"
rpc_url = "https://api.mainnet-beta.solana.com"

# Raydium AMM program ID
program_id = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"

[database]
max_connections = 5

[api]
port = 3000